server:
  port: 8087
spring:
#  main:
#    allow-bean-definition-overriding=true
  data:
    mongodb:
      uri: mongodb://localhost:27017/registerdb
  application:
    name: archive-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost


